server:
  port: 888

spring:
  datasource:
    druid:
      # 数据库访问配置, 使用druid数据源
      # 数据源 mysql
      #mysql:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      #driver-class-name: com.mysql.jdbc.Driver
      #url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
      url: jdbc:sqlserver://localhost:1433;DatabaseName=jh_safety
      username: sa
      password: zw_admin%8

        
      # 连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 连接等待超时时间
      max-wait: 30000
      # 配置检测可以关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      #mysql
      #validation-query: select '1' from dual
      #sql server
      validation-query: select '1'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters, 去掉后监控界面sql无法统计, 'wall'用于防火墙
      filters: stat,wall
      # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
      aop-patterns: com.gao.servie.*
      
    
      # WebStatFilter配置
      web-stat-filter:
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤的格式
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      # StatViewServlet配置 
      stat-view-servlet:
        enabled: true
        # 访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
        # 是否能够重置数据
        reset-enable: false
        # 需要账号密码才能访问控制台
        login-username: druid
        login-password: druid
        # IP白名单
        allow: 127.0.0.1
        #　IP黑名单（共同存在时，deny优先于allow）
        # deny: 192.168.1.218
      
      # 配置StatFilter
      filter: 
        stat: 
          log-slow-sql: true 

#QQ邮箱配置
  mail:
    host: smtp.qq.com
    username: 1772525701@qq.com
    password: nmvswdpywjmhbjia
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  application:
    name: admin-server
  #thymeleaf模版前缀
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
  

#163邮箱配置
#  mail:
#    host: smtp.163.com
#    username: 13213833671@163.com
#    password: 163com
#    default-encoding: UTF-8
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
      
    
#debug: true

#Actuator健康检查
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
info:
  app:
    encoding: '@project.build.sourceEncoding@'
    java.source: '@java.version@'
    java.traget: '@java.version@'




































